apiVersion: batch/v1
kind: Job
metadata:
  name: syncjob
  annotations:
    argocd.argoproj.io/hook: PreSync
    # argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: testinghook
        # image: apline:latest
        command: ["/bin/sh"]
        args: ["-c", "echo Hi, PreSync;"]
      restartPolicy: Never
  backoffLimit: 0

  